AGENDAMENTOS = [
    {
        "paciente": "Maria da Silva",
        "cpf": "123.456.789-00",
        "medico": "Dr. João Pereira",
        "especialidade": "Cardiologia",
        "data": "2026-07-25",
        "horario": "09:00",
        "convenio": "Unimed",
        "status": "Confirmado",
    },
    {
        "paciente": "José Santos",
        "cpf": "987.654.321-00",
        "medico": "Dra. Ana Costa",
        "especialidade": "Dermatologia",
        "data": "2026-07-25",
        "horario": "10:30",
        "convenio": "Bradesco Saúde",
        "status": "Aguardando confirmação",
    },
    {
        "paciente": "Carla Oliveira",
        "cpf": "456.789.123-00",
        "medico": "Dr. Paulo Mendes",
        "especialidade": "Ortopedia",
        "data": "2026-07-26",
        "horario": "14:00",
        "convenio": "SulAmérica",
        "status": "Confirmado",
    },
    {
        "paciente": "Roberto Lima",
        "cpf": "321.654.987-00",
        "medico": "Dra. Fernanda Alves",
        "especialidade": "Clínico Geral",
        "data": "2026-07-26",
        "horario": "16:30",
        "convenio": "Particular",
        "status": "Cancelado",
    },
    {
        "paciente": "Juliana Rocha",
        "cpf": "654.321.987-00",
        "medico": "Dr. João Pereira",
        "especialidade": "Cardiologia",
        "data": "2026-07-27",
        "horario": "08:00",
        "convenio": "Amil",
        "status": "Confirmado",
    },
    {
        "paciente": "Pedro Almeida",
        "cpf": "789.123.456-00",
        "medico": "Dra. Ana Costa",
        "especialidade": "Dermatologia",
        "data": "2026-07-27",
        "horario": "11:15",
        "convenio": "Unimed",
        "status": "Remarcado",
    },
    {
        "paciente": "Fernanda Souza",
        "cpf": "159.753.486-00",
        "medico": "Dr. Paulo Mendes",
        "especialidade": "Ortopedia",
        "data": "2026-07-28",
        "horario": "13:45",
        "convenio": "Bradesco Saúde",
        "status": "Confirmado",
    },
    {
        "paciente": "Lucas Martins",
        "cpf": "753.159.486-00",
        "medico": "Dra. Fernanda Alves",
        "especialidade": "Clínico Geral",
        "data": "2026-07-28",
        "horario": "17:00",
        "convenio": "Particular",
        "status": "Aguardando confirmação",
    },
]